### ISSUE TITLE
TBC Classic errors:

### ISSUE THREAD

**Issue by yoshimo** [smaitch/Grail#277]
BC Classic is some sort of hybrid between classic and 9.1 api, so  right now it is a nasty

I made the following changes to process

`		existsClassic = (WOW_PROJECT_ID == WOW_PROJECT_BURNING_CRUSADE_CLASSIC),`
in Grail.lua

i removed everything inside `_SendQuestChoiceList` to avoid an error

```
Message: ..\AddOns\Grail\Grail.lua line 11374:
   '}' expected (to close '{' at line 11243) near '['
```
might be my own fault in my local patched version though.

Now we have 

```
Message: ..\AddOns\Grail\Grail.lua line 8548:
   attempt to concatenate local 'soughtParameter' (a nil value)
```

which might have to do with Bloodelfs being new in that expansion

**Comment by smaitch** [comment]
I think the existsClassic definition might be best to be expanded so instead of that one line two things should happen:
`		existsClassicBasic = (WOW_PROJECT_ID == WOW_PROJECT_CLASSIC),
		existsClassicBurningCrusade = (WOW_PROJECT_ID == WOW_PROJECT_BURNING_CRUSADE_CLASSIC),
`
and then just before the code that looks like:`
					if self.existsClassic then
						self.environment = "_classic_"
					end
`
the following can be added:`
					self.existsClassic = self.existsClassicBasic or self.existsClassicBurningCrusade,
`

I believe the issue with the `_SendQuestChoiceList` error is fixed with the code I pushed today.

**Comment by smaitch** [comment]
Having a separation between `self.existsClassicBasic` and `self.existsClassicBurningCrusade` might allow detecting things that are appearing in the Burning Crusade version such that both the normal classic and BC classic code can be the same with proper detections as needed.

**Comment by Wyr3d** [comment]
So I tried this, and it didn't seem to work. Do you have a working fix you can upload and link?

**Comment by yoshimo** [comment]
https://github.com/yoshimo/Grail/tree/bcc 
Not completely done yet but it should be able to record things

**Comment by Wyr3d** [comment]
Still getting an issue where Wholly complains that it needs Grail version 110 or later to work

**Comment by yoshimo** [comment]
The branch should give you 115 if I made no mistake when rebasing.

**Comment by Wyr3d** [comment]
So is wholly at fault then? Coz I swapped out my existing Grail for a copy from your link

**Comment by Wyr3d** [comment]
Okay, so I added:

**else
    if not frame.SetBackdrop then
        Mixin(frame, BackdropTemplateMixin)
    end**

Just before 

    **frame:SetBackdrop({**

This got the frame to display at least, but there's no quest text, and now it's throwing up the following issue:

Date: 2021-05-30 07:10:29
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Wholly\Wholly.lua line 2605:
   attempt to index field 'color' (a nil value)
Debug:
   [string "=[C]"]: ?
   [string "@Wholly\Wholly.lua"]:2605: _PrettyQuestCountString()
   [string "@Wholly\Wholly.lua"]:1839: _FilterQuests()
   [string "@Wholly\Wholly.lua"]:1871: _FilterPanelQuests()
   [string "@Wholly\Wholly.lua"]:3494: ScrollFrame_Update()
   [string "@Wholly\Wholly.lua"]:3381: ScrollFrame_Update_WithCombatCheck()
   [string "@Wholly\Wholly.lua"]:1883: _ForcePanelMapArea()
   [string "@Wholly\Wholly.lua"]:2769: _ProcessInitialUpdate()
   [string "@Wholly\Wholly.lua"]:2539: OnShow()
   [string "@Wholly\Wholly.lua"]:4023:
      Wholly\Wholly.lua:4022
   [string "=[C]"]: Show()
   [string "@Wholly\Wholly.lua"]:4362: ToggleUI()
   [string "@Wholly\Wholly.lua"]:4185: SlashCommand()
   [string "@Wholly\Wholly.lua"]:1993: ?()
   [string "@..\FrameXML\ChatFrame.lua"]:4825: ChatEdit_ParseText()
   [string "@..\FrameXML\ChatFrame.lua"]:4488: ChatEdit_SendText()
   [string "@..\FrameXML\ChatFrame.lua"]:2916:
      ..\FrameXML\ChatFrame.lua:2909
   [string "=[C]"]: UseAction()
   [string "@..\FrameXML\SecureTemplates.lua"]:338: handler()
   [string "@..\FrameXML\SecureTemplates.lua"]:616: SecureActionButton_OnClick()
   [string "*:OnClick"]:4:
      [string "*:OnClick"]:1
Locals:

AddOns:
  Swatter, v1.13.6652 (SwimmingSeadragon)
  WowheadLooter, v20501
  AccountantClassic, vv2.12.08.20501.00
  Armory, vv1.1.1
  ATTClassic, v0.5.7
  ButtonForge, v1.0.5-classic-TBC
  DBMCore, v2.5.4
  DBMStatusBarTimers, v
  ExtendedMapZoneInfoForClassic, v1.5
  FleecingTip, v113.1770(200720)
  GatherMate2, v1.46.0-classic
  Grail, v115
  GrailNPCsclassic, v27178
  GrailNPCsclassicenUS, v33302
  GrailQuestsclassic, v27178
  GrailQuestsclassicenUS, v33302
  HandyNotes, vv1.6.3
  LetMeFly, v1.0
  SilverDragon, vv11302.0
  SilverDragonClassic, vv11302.0
  SlideBar, v1.13.6668 (SwimmingSeadragon)
  Spy, v1.1.2
  TradeSkillMaster, vv4.10.40
  TradeSkillMasterAppHelper, vv4.0.14
  Wholly, v079
  WIM, v3.9.1
  BlizRuntimeLib_enUS v2.5.1.20501 <none>
  (ck=2ef)

**Comment by smaitch** [comment]
I believe this is no longer happening with the latest GitHub code based on comments in https://github.com/smaitch/Grail/issues/278

**Comment by Wyr3d** [comment]
Yup, you can go ahead an close the issues I believe
